drop table #Rendeles

declare @RendelesSzam varchar(50), @ToleranceText varchar(50)
set @RendelesSzam = '489090'

CREATE TABLE #Rendeles (ID int IDENTITY (1,1) PRIMARY KEY, PreStr varchar (50), Data varchar(max), PostStr varchar(50))

declare
@RendelesAz int,
@TermekKod int,
@RendSz varchar(20),
@PhxRendSz varchar(20),
@VevoRendSz varchar(20),
@Vevo varchar(50),
@Felhasznalo varchar(50),
@Hatarido datetime,
@ExtrKtsg float,
@ExtrPenznem varchar(10),
@ErtTerulet varchar(20),
@RKonfekcio varchar(50),
@LevelSzama varchar(20),
@LevelDatuma datetime,
@RMegj varchar(50),
@RRogzit varchar(50),
@RRogzIdo datetime,
@RModosit varchar(50),
@RModIdo datetime,
@RModMezok decimal(28, 0),
@Enged bit,
@Vissza bit,
@IgertHatarido datetime,
@AjanlatSzam varchar(20),
@SapRevizio smallint,
@FAutoUpdate bit,
--@RendelesAz int,
@TetelSrsz int,
@Cikkszam varchar(20),
@Specifikacio varchar(100),
@Atmero decimal(9, 2),
@AtmeroMe smallint,
@psi decimal(9, 2),
@MPa decimal(9, 2),
@Lang bit,
@Bg bit,
@Kg bit,
@Pa bit,
@Kv bit,
@KgInter bit,
@KvMua bit,
@KvFedHelix bit,
@KvNFedHelix bit,
@H2S smallint,
@Tipus varchar(50),
@Csatl1 varchar(50),
@Csatl1Rsz varchar(20),
@Csatl1MaxAtmero float,
@Csatl1MaxAtmeroMe int,
@Csatl2 varchar(50),
@Csatl2Rsz varchar(20),
@Csatl2MaxAtmero float,
@Csatl2MaxAtmeroMe int,
@DarabSzam float,
@Hossz float,
@HosszMe varchar(10),
@HosszMe2 smallint,
@TErtek float,
@TPenznem varchar(50),
@OsszeallRsz varchar(50),
@Konstrukcio varchar(50),
@Konstrukcio2 varchar(50),
@KonstrukcioMaxAtmero float,
@KonstrukcioMaxAtmeroMe int,
@TKonfekcio varchar(50),
@TKonfekDatum datetime,
@NormaIdo float,
@DbjDatum datetime,
@MuvDatum datetime,
@KonstrDatum datetime,
@FszHatarido datetime,
@FszBeerk datetime,
@Anyag varchar(50),
@Csomagolas varchar(50),
@Egyeb varchar(50),
@TMegj varchar(50),
@TRogzit varchar(50),
@TRogzIdo datetime,
@TModosit varchar(50),
@TModIdo datetime,
@ModMezok decimal(9, 0),
@Torolt bit,
@Beszolg bit,
@TModHatarido datetime,
@BeszolgIdo datetime,
@BeszolgDb float,
@BeszolgHossz float,
@Tomeg float,
@GyartasInd datetime,
@BefejezoMuv datetime,
@AccListExist bit,
@AccListDate datetime,
@AccCreator varchar(50),
@BelsoHuvely varchar(20),
@BhAnyag varchar(50),
@Huvely varchar(20),
@Spiralkup varchar(20),
@Emelobilincs varchar(20),
@EbMeret float,
@BiztBilincs varchar(20),
@BbMeret float,
@TomitoGyuru1 varchar(20),
@TomitoGyuru2 varchar(20),
@Feneklap1 varchar(20),
@Feneklap2 varchar(20),
@NyomPrBilincs1 varchar(20),
@NyomPrBilincs2 varchar(20),
@VedoHuvely varchar(20),
@OsztottHuvely varchar(20),
@Egyebek varchar(500),
@AtveteliKesz bit,
@AtveteliIdopont datetime,
@AtvetelitKeszitette varchar(50),
@Inspector varchar(50),
@InspectorMegj varchar(max),
@SapTypeOfCoupling1 varchar(250),
@SapTypeOfCoupling2 varchar(250),
@TAutoUpdate bit,
@Marking varchar(50),
@Standard varchar(50),
@StandardText varchar(50),
@TypeOfPacking varchar(50),
@WorkingPressure float,
@WorkingPressureUnit char(10),
@DesignPressure float,
@DesignPressureUnit char(10),
@TestPressure float,
@TestPressureUnit char(10),
@SafetyFactor float,
@TypeOfLining varchar(50),
@MaxDesignTemperature float,
@MinDesignTemperature float,
@AccListMailDate datetime,
@AccListMailSender varchar(50),
@AccListMailSent bit,
@MarkingId int

declare crs cursor for
select
	rf.RendelesAz, TermekKod, RendSz, PhxRendSz, VevoRendSz, Vevo, Felhasznalo, 
	Hatarido, ExtrKtsg, ExtrPenznem, ErtTerulet, RKonfekcio, LevelSzama, 
	LevelDatuma, RMegj, RRogzit, RRogzIdo, RModosit, RModIdo, RModMezok,
	Enged, Vissza, IgertHatarido, AjanlatSzam, SapRevizio, FAutoUpdate,
	TetelSrsz, Cikkszam, Specifikacio, Atmero, AtmeroMe, psi, MPa, 
	Lang, Bg, Kg, Pa, Kv, KgInter, KvMua, KvFedHelix, KvNFedHelix, H2S, Tipus, 
	Csatl1, Csatl1Rsz, Csatl1MaxAtmero, Csatl1MaxAtmeroMe, Csatl2, Csatl2Rsz, 
	Csatl2MaxAtmero, Csatl2MaxAtmeroMe, DarabSzam, Hossz, HosszMe, HosszMe2, 
	TErtek, TPenznem, OsszeallRsz, Konstrukcio, Konstrukcio2, KonstrukcioMaxAtmero, 
	KonstrukcioMaxAtmeroMe, TKonfekcio, TKonfekDatum, NormaIdo, DbjDatum, MuvDatum, 
	KonstrDatum, FszHatarido, FszBeerk, Anyag, Csomagolas, Egyeb, TMegj, 
	TRogzit, TRogzIdo, TModosit, TModIdo, ModMezok, Beszolg, TModHatarido, 
	BeszolgIdo, BeszolgDb, BeszolgHossz, Tomeg, GyartasInd, BefejezoMuv, 
	AccListExist, AccListDate, AccCreator, BelsoHuvely, BhAnyag, Huvely, Spiralkup, 
	Emelobilincs, EbMeret, BiztBilincs, BbMeret, TomitoGyuru1, TomitoGyuru2, 
	Feneklap1, Feneklap2, NyomPrBilincs1, NyomPrBilincs2, VedoHuvely, OsztottHuvely, 
	Egyebek, AtveteliKesz, AtveteliIdopont, AtvetelitKeszitette, Inspector, 
	InspectorMegj, SapTypeOfCoupling1, SapTypeOfCoupling2, TAutoUpdate, 
	Marking, Standard, StandardText, TypeOfPacking, WorkingPressure, WorkingPressureUnit, 
	DesignPressure, DesignPressureUnit, TestPressure, TestPressureUnit, SafetyFactor, 
	TypeOfLining, MaxDesignTemperature, MinDesignTemperature, AccListMailDate, 
	AccListMailSender, AccListMailSent, MarkingId
from
	RendelesFej rf,
	RendelesTetel rt
where
	rf.RendelesAz = rt.RendelesAz
	and RendSz = @RendelesSzam
	and rf.Torolt = 0
	and rt.Torolt = 0
order by
	TetelSrsz

open crs
FETCH NEXT FROM crs 
INTO
	-- RendelesFej
	@RendelesAz,
	@TermekKod,
	@RendSz,
	@PhxRendSz,
	@VevoRendSz,
	@Vevo,
	@Felhasznalo,
	@Hatarido,
	@ExtrKtsg,
	@ExtrPenznem,
	@ErtTerulet,
	@RKonfekcio,
	@LevelSzama,
	@LevelDatuma,
	@RMegj,
	@RRogzit,
	@RRogzIdo,
	@RModosit,
	@RModIdo,
	@RModMezok,
	@Enged,
	@Vissza,
	@IgertHatarido,
	@AjanlatSzam,
	@SapRevizio,
	@FAutoUpdate,
	-- RendelesTetel
	@TetelSrsz,
	@Cikkszam,
	@Specifikacio,
	@Atmero,
	@AtmeroMe,
	@psi,
	@MPa,
	@Lang,
	@Bg,
	@Kg,
	@Pa,
	@Kv,
	@KgInter,
	@KvMua,
	@KvFedHelix,
	@KvNFedHelix,
	@H2S,
	@Tipus,
	@Csatl1,
	@Csatl1Rsz,
	@Csatl1MaxAtmero,
	@Csatl1MaxAtmeroMe,
	@Csatl2,
	@Csatl2Rsz,
	@Csatl2MaxAtmero,
	@Csatl2MaxAtmeroMe,
	@DarabSzam,
	@Hossz,
	@HosszMe,
	@HosszMe2,
	@TErtek,
	@TPenznem,
	@OsszeallRsz,
	@Konstrukcio,
	@Konstrukcio2,
	@KonstrukcioMaxAtmero,
	@KonstrukcioMaxAtmeroMe,
	@TKonfekcio,
	@TKonfekDatum,
	@NormaIdo,
	@DbjDatum,
	@MuvDatum,
	@KonstrDatum,
	@FszHatarido,
	@FszBeerk,
	@Anyag,
	@Csomagolas,
	@Egyeb,
	@TMegj,
	@TRogzit,
	@TRogzIdo,
	@TModosit,
	@TModIdo,
	@ModMezok,
	--@Torolt,
	@Beszolg,
	@TModHatarido,
	@BeszolgIdo,
	@BeszolgDb,
	@BeszolgHossz,
	@Tomeg,
	@GyartasInd,
	@BefejezoMuv,
	@AccListExist,
	@AccListDate,
	@AccCreator,
	@BelsoHuvely,
	@BhAnyag,
	@Huvely,
	@Spiralkup,
	@Emelobilincs,
	@EbMeret,
	@BiztBilincs,
	@BbMeret,
	@TomitoGyuru1,
	@TomitoGyuru2,
	@Feneklap1,
	@Feneklap2,
	@NyomPrBilincs1,
	@NyomPrBilincs2,
	@VedoHuvely,
	@OsztottHuvely,
	@Egyebek,
	@AtveteliKesz,
	@AtveteliIdopont,
	@AtvetelitKeszitette,
	@Inspector,
	@InspectorMegj,
	@SapTypeOfCoupling1,
	@SapTypeOfCoupling2,
	@TAutoUpdate,
	@Marking,
	@Standard,
	@StandardText,
	@TypeOfPacking,
	@WorkingPressure,
	@WorkingPressureUnit,
	@DesignPressure,
	@DesignPressureUnit,
	@TestPressure,
	@TestPressureUnit,
	@SafetyFactor,
	@TypeOfLining,
	@MaxDesignTemperature,
	@MinDesignTemperature,
	@AccListMailDate,
	@AccListMailSender,
	@AccListMailSent,
	@MarkingId

WHILE @@FETCH_STATUS = 0
BEGIN
	
	insert into #Rendeles (PreStr, Data, PostStr) Values('A rendelés ', @TetelSrsz, ' jelû tétele')
	insert into #Rendeles (PreStr, Data, PostStr) Values('Tömlõ neve ', IsNull(@Tipus, ''), '')
	insert into #Rendeles (PreStr, Data, PostStr) Values('Szabvány', IsNull(@Standard, ''), '')
	insert into #Rendeles (PreStr, Data, PostStr) Values('Megnevezés', IsNull(@Specifikacio, ''), '')
	execute sp_GetToleranceText @Atmero, @ToleranceText output
	insert into #Rendeles (PreStr, Data, PostStr) Values('Csõmagméret  (külátm.)', IsNull(@ToleranceText, ''), '')
	insert into #Rendeles (PreStr, Data, PostStr) Values('Konstrukciós lap száma', IsNull(@Konstrukcio, ''), '')
	--insert into #Rendeles (PreStr, Data, PostStr) Values('Anyagnorma száma', IsNull(@Konstrukcio, ''), '')
	insert into #Rendeles (PreStr, Data, PostStr) Values('Összeállitási rajz', IsNull(@OsszeallRsz, ''), '')
	insert into #Rendeles (PreStr, Data, PostStr) Values('Csatlakozó rsz."A"', IsNull(@Csatl1Rsz, ''), '')

	FETCH NEXT FROM crs 
	INTO
		-- RendelesFej
		@RendelesAz,
		@TermekKod,
		@RendSz,
		@PhxRendSz,
		@VevoRendSz,
		@Vevo,
		@Felhasznalo,
		@Hatarido,
		@ExtrKtsg,
		@ExtrPenznem,
		@ErtTerulet,
		@RKonfekcio,
		@LevelSzama,
		@LevelDatuma,
		@RMegj,
		@RRogzit,
		@RRogzIdo,
		@RModosit,
		@RModIdo,
		@RModMezok,
		@Enged,
		@Vissza,
		@IgertHatarido,
		@AjanlatSzam,
		@SapRevizio,
		@FAutoUpdate,
		-- RendelesTetel
		@TetelSrsz,
		@Cikkszam,
		@Specifikacio,
		@Atmero,
		@AtmeroMe,
		@psi,
		@MPa,
		@Lang,
		@Bg,
		@Kg,
		@Pa,
		@Kv,
		@KgInter,
		@KvMua,
		@KvFedHelix,
		@KvNFedHelix,
		@H2S,
		@Tipus,
		@Csatl1,
		@Csatl1Rsz,
		@Csatl1MaxAtmero,
		@Csatl1MaxAtmeroMe,
		@Csatl2,
		@Csatl2Rsz,
		@Csatl2MaxAtmero,
		@Csatl2MaxAtmeroMe,
		@DarabSzam,
		@Hossz,
		@HosszMe,
		@HosszMe2,
		@TErtek,
		@TPenznem,
		@OsszeallRsz,
		@Konstrukcio,
		@Konstrukcio2,
		@KonstrukcioMaxAtmero,
		@KonstrukcioMaxAtmeroMe,
		@TKonfekcio,
		@TKonfekDatum,
		@NormaIdo,
		@DbjDatum,
		@MuvDatum,
		@KonstrDatum,
		@FszHatarido,
		@FszBeerk,
		@Anyag,
		@Csomagolas,
		@Egyeb,
		@TMegj,
		@TRogzit,
		@TRogzIdo,
		@TModosit,
		@TModIdo,
		@ModMezok,
		@Beszolg,
		@TModHatarido,
		@BeszolgIdo,
		@BeszolgDb,
		@BeszolgHossz,
		@Tomeg,
		@GyartasInd,
		@BefejezoMuv,
		@AccListExist,
		@AccListDate,
		@AccCreator,
		@BelsoHuvely,
		@BhAnyag,
		@Huvely,
		@Spiralkup,
		@Emelobilincs,
		@EbMeret,
		@BiztBilincs,
		@BbMeret,
		@TomitoGyuru1,
		@TomitoGyuru2,
		@Feneklap1,
		@Feneklap2,
		@NyomPrBilincs1,
		@NyomPrBilincs2,
		@VedoHuvely,
		@OsztottHuvely,
		@Egyebek,
		@AtveteliKesz,
		@AtveteliIdopont,
		@AtvetelitKeszitette,
		@Inspector,
		@InspectorMegj,
		@SapTypeOfCoupling1,
		@SapTypeOfCoupling2,
		@TAutoUpdate,
		@Marking,
		@Standard,
		@StandardText,
		@TypeOfPacking,
		@WorkingPressure,
		@WorkingPressureUnit,
		@DesignPressure,
		@DesignPressureUnit,
		@TestPressure,
		@TestPressureUnit,
		@SafetyFactor,
		@TypeOfLining,
		@MaxDesignTemperature,
		@MinDesignTemperature,
		@AccListMailDate,
		@AccListMailSender,
		@AccListMailSent,
		@MarkingId
end

close crs
deallocate crs

select * from #Rendeles
